### ISSUE TITLE
Immersive Engineering's hemp no longer supported

### ISSUE THREAD

**Issue by WrongWeekend** [AustereTony-MCMods/Plant-Biomes#3]
Opening a new ticket for the sake of organization.

In previous versions of the mod (1.3.6 and prior I think) Immersive Engineering's hemp ("immersiveengineering:hemp"/"tile.immersiveengineering.hemp.name") could be added to the list using /pb commands and worked as intended. As of 1.4.0 it is no longer possible to configure IE's hemp plant because a "This plant is unsupported" error is given. Attempting to reload from manual configuration with hemp added also gives an error.

Perhaps having the plant work was unintentional, but if it wasn't supposed to work, I would suggest officially supporting it.

EDIT: The same issue applies to Dynamic Trees' version of cocoa beans ("dynamictrees:fruitcocoa") Previously worked, but now does not.

**Comment by AustereTony-MCMods** [comment]
Since 1.3.12 Plant Biomes using new filter for supported plants (plant class name check), so it will ignore any plant i didn't mention [here](https://github.com/AustereTony-MCMods/Plant-Biomes/blob/info/supported.txt). It will ensure what plants are _fully_ supports all settings. The problem was some modded plants could be customized and it even affected bonemeal behavior, but not plant growth itself - it grown over time despite settings. Almost every modded plants implements its own growth behavior and i need to add biome check there. So IE's hemp ([link](https://github.com/BluSunrize/ImmersiveEngineering/blob/116629e052adeb9bc061afc4d8087bd641cd25f4/src/main/java/blusunrize/immersiveengineering/common/blocks/plant/BlockIECrop.java#L251)) and Dynamic Trees ([link](https://github.com/ferreusveritas/DynamicTrees/blob/619d419e7c6904ae62d21b48d48a7b4b76571593/src/main/java/com/ferreusveritas/dynamictrees/blocks/BlockFruit.java#L60)) does.

I accepted suggestion and will add support for these plants in next patch.

**Comment by AustereTony-MCMods** [comment]
Version 1.4.6 released and now it fully supports IE's hemp and Dynamic Trees saplings, fruits and cocoa (also supports BOP addon plants).

**Comment by AustereTony-MCMods** [comment]
If there are no questions, i consider issue closed.
